export let settings = {
	pixelScale: 5,
	backgroundColor: "#111"
}

export function Map(w, h) {
	this.map = [];
	for(let i = 0; i < h; i++){
		this.map.push([]);
		for(let j = 0; j < w; j++){
			this.map[i].push(0);
		}
	}
	console.log(this.map)
	return this.map;
}


// +- auto generated by my python scripts
export const palette = [
	{ label: "BedrockBlock", color: "red", index:1},
	{ label: "BerryBushBlock", color: "red", index:1},
	{ label: "BirchLeaves", color: "red", index:1},
	{ label: "BirchSapling", color: "red", index:1},
	{ label: "BirchTrunk", color: "red", index:1},
	{ label: "BrickBackgroundBlock", color: "red", index:0},
	{ label: "BrickBlock", color: "red", index:1},
	{ label: "CoalBlock", color: "red", index:1},
	{ label: "CreepBlock", color: "red", index:1},
	{ label: "DirtBackgroundBlock", color: "red", index:0},
	{ label: "DirtBlock", color: "red", index:1},
	{ label: "DirtBlockSurface", color: "red", index:1},
	{ label: "GoldBlock", color: "red", index:1},
	{ label: "Grass", color: "red", index:1},
	{ label: "IronBlock", color: "red", index:1},
	{ label: "IronSpikeBlock", color: "red", index:1},
	{ label: "LadderBlock", color: "red", index:1},
	{ label: "LavaBlock", color: "red", index:1},
	{ label: "MagmaBlock", color: "red", index:1},
	{ label: "MithrilBlock", color: "red", index:1},
	{ label: "ObsidianBlock", color: "red", index:1},
	{ label: "PlatformBlock", color: "red", index:1},
	{ label: "PlatformBlockCollapsed", color: "red", index:1},
	//{ label: "PlatformBlockCollapsedTeamOverlay", color: "red", index:1},
	//{ label: "PlatformBlockTeamOverlay", color: "red", index:1},
	{ label: "PumpkinSeedBlock", color: "red", index:1},
	{ label: "ShingleBlock", color: "red", index:1},
	{ label: "Snow", color: "red", index:1},
	{ label: "StairBrickBlock", color: "red", index:1},
	{ label: "StairWoodBlock", color: "red", index:1},
	{ label: "SteelBlock", color: "red", index:1},
	{ label: "StoneBackgroundBlock", color: "red", index:0},
	{ label: "StoneBlock", color: "red", index:1},
	{ label: "TorchBlock", color: "red", index:1},
	{ label: "VineBlock", color: "red", index:1},
	{ label: "WaterBlock", color: "red", index:1},
	{ label: "WaterBlockSurface", color: "red", index:1},
	{ label: "WheatBlock", color: "red", index:1},
	{ label: "WoodBackgroundBlock", color: "red", index:0},
	{ label: "WoodBlock", color: "red", index:1},
	{ label: "WoodSpikeBlock", color: "red", index:1},
	//{ label: "WoodSpikeBlockTeamOverlay", color: "red", index:1}
];
